<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
	<!--Ensures the generator is using the recommended rules created by the .NET team-->
	<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
	  
	<!--Enables the project to act as a generator and work with the Roslyn compiler, making debugging of the generator possible-->
	<IsRoslynComponent>true</IsRoslynComponent>
	  
	<!--This prevents the project build from being included in output, which is ideal since the generator is meant to be compile-time only-->
	<IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="*" />
		
		<PackageReference Include="Microsoft.Management.Infrastructure" Version="3.0.0" />
		
		<PackageReference Include="PolySharp" Version="*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<!--<ItemGroup>
		<ProjectReference Include="..\SourceGenerator.SharedLibrary\SourceGenerator.SharedLibrary.csproj" OutputItemType="Analyzer" />
	</ItemGroup>-->

</Project>
